# Taps
tap "homebrew/cask"

# Formulae
brew "automake"
brew "ccat"
brew "git"
brew "gnu-sed"
brew "go"
brew "gpg"
brew "htop"
brew "jq"
brew "node"
brew "pipenv"
brew "python"
brew "telnet"
brew "tldr"
brew "tmux"
brew "tree"
brew "watch"
brew "wget"

# Casks
cask "brave-browser", args: { force: true }
cask "google-drive", args: { force: true }
cask "google-chrome", args: { force: true }
cask "iterm2", args: { force: true }
cask "keepassxc", args: { force: true }
cask "slack", args: { force: true }
cask "rectangle", args: { force: true }
cask "spotify", args: { force: true }
cask "zoom", args: { force: true }
