# stock ubuntu bash ls colors
export CLICOLOR=1
export LSCOLORS=GxBxCxDxexegedabagaced

parse_git_branch() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\[\033[01;32m\]\u {\W} > \[\033[00m\]"

# useful commands
alias ll="ls -al"

# here is my super cool reddit console app
alias reddit="python ~/dev/reddit/some.py"

# tmux kill commands
alias killw="tmux kill-window"
alias killp="tmux kill-pane"
alias kills="tmux kill-session"

alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias subl="/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text"
alias psme="ps aux | grep zmwieand"

# Android Studios Path
export ANDROID_HOME=/Users/zmwieand/Library/Android/sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

