# Allows me to add the git branch to my promt
setopt PROMPT_SUBST

# History settings
HISTFILE="$HOME/.zsh_history"
HISTSIZE=100000
SAVEHIST=100000
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.

# Home/End/Delete keys
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line
bindkey "\e[1~" beginning-of-line
bindkey "\e[4~" end-of-line
bindkey  "^[[3~"  delete-char

# Get the current git branch for PS1
function parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/⌥ \1 /'
  # insertions=$(git diff --stat | grep -Eo "\d+ insertions" | grep -Eo "\d+")
  # deletions=$(git diff --stat | grep -Eo "\d+ deletions" | grep -Eo "\d+")
  # echo "${branch} +${insertions}/-${deletions} "
}

# Change to the root of the git repo directory
function gitroot() {
  cd $(git rev-parse --show-toplevel)
}

# Stock ubuntu bash ls colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
export PS1='%F{81}λ %F{124}$(parse_git_branch)%F{81}{%1~} > %f'

# Aliases
alias ifme="curl ifconfig.me && echo \"\" && ifconfig | grep -E \"\d+\.\d+\.\d+\.\d+\""
alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
alias grep='grep --color'
alias ll="ls -al"
alias ls='ls -GFh'
alias ll='ls -laGFh'
alias psme="ps aux | grep $(whoami)"
alias subl="/Applications/Sublime\ Text.app/Contents/MacOS/Sublime\ Text"
alias weather="curl wttr.in/14086"

# Kubernetes Aliases
alias k="kubectl"
alias kubeconfig_update="/usr/local/bin/update_kubeconfig.sh"
alias proxy="/usr/local/bin/kube_proxy.sh"

# tmux kill commands
alias killw="tmux kill-window"
alias killp="tmux kill-pane"
alias kills="tmux kill-session"

# So tar does not create hidden files
export COPYFILE_DISABLE=true
